"use client";

import {
  Activity, AlertCircle, ArrowRight, Award, BarChart3, Bell, BookOpen,
  Building2, CalendarDays, Check, CheckCircle2, ChevronDown, ChevronLeft,
  ChevronRight, ClipboardCheck, Clock3, Download, FileBarChart, FileSpreadsheet,
  FileText, Filter, GraduationCap, HelpCircle, History, LayoutDashboard, Lock,
  LogOut, Menu, MoreHorizontal, Plus, Printer, RotateCcw, School, Search,
  Settings, ShieldCheck, TrendingDown, TrendingUp, Upload, UserCog, UserRound,
  Users, WandSparkles, X,
} from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import {
  createAppsScriptDataService,
  createLocalDataService,
  normalizeAppsScriptStudent,
} from "./lib/data-service";

type Role = "guru" | "admin";
type Subject = "Bahasa Melayu" | "Matematik";
type Cycle = "TOV" | "OTI 1" | "AR 1" | "OTI 2" | "AR 2" | "OTI 3" | "AR 3" | "ETR";
type View = "dashboard" | "students" | "headcount" | "interventions" | "analysis" | "reports" | "schools" | "submissions" | "users" | "audit" | "settings";
type Student = { id:string; name:string; year:number; className:string; subject:Subject; status:"Aktif"|"Pelepasan"; startDate:string; skills:Record<Cycle,number>; intervention:"Tiada"|"Aktif"|"Selesai"|"Perlu susulan" };
type Intervention = { id:string; studentId:string; issue:string; action:string; method:string; start:string; review:string; status:string };

const cycles:Cycle[] = ["TOV","OTI 1","AR 1","OTI 2","AR 2","OTI 3","AR 3","ETR"];
const skillOptions = Array.from({length:32},(_,i)=>i+1);
const S=(TOV:number,AR1:number,AR2:number,AR3:number,ETR:number):Record<Cycle,number>=>({TOV,"OTI 1":Math.max(TOV,AR1-1),"AR 1":AR1,"OTI 2":Math.max(AR1,AR2-1),"AR 2":AR2,"OTI 3":Math.max(AR2,AR3-1),"AR 3":AR3,ETR});
const seed:Student[]=[
  {id:"ST001",name:"Nur Mira Sofea",year:2,className:"2 Bijak",subject:"Bahasa Melayu",status:"Aktif",startDate:"2026-01-12",skills:S(5,7,8,10,16),intervention:"Aktif"},
  {id:"ST002",name:"Muhammad Ali Haziq",year:2,className:"2 Bijak",subject:"Bahasa Melayu",status:"Aktif",startDate:"2026-01-12",skills:S(4,5,6,6,12),intervention:"Perlu susulan"},
  {id:"ST003",name:"Siti Aisyah Hana",year:3,className:"3 Amanah",subject:"Bahasa Melayu",status:"Aktif",startDate:"2025-03-03",skills:S(8,9,10,11,18),intervention:"Aktif"},
  {id:"ST004",name:"Amin Danish",year:3,className:"3 Amanah",subject:"Bahasa Melayu",status:"Aktif",startDate:"2025-03-03",skills:S(15,18,21,24,27),intervention:"Tiada"},
  {id:"ST005",name:"Puteri Balqis",year:1,className:"1 Cekal",subject:"Bahasa Melayu",status:"Aktif",startDate:"2026-02-02",skills:S(2,4,6,9,14),intervention:"Selesai"},
  {id:"ST006",name:"Daniel Lee Jun Wei",year:2,className:"2 Bestari",subject:"Matematik",status:"Aktif",startDate:"2026-01-12",skills:S(10,14,19,25,28),intervention:"Tiada"},
  {id:"ST007",name:"Ariff Iman",year:1,className:"1 Cekal",subject:"Bahasa Melayu",status:"Aktif",startDate:"2026-02-02",skills:S(1,3,4,5,10),intervention:"Aktif"},
  {id:"ST008",name:"Kavitha Nair",year:3,className:"3 Bestari",subject:"Bahasa Melayu",status:"Pelepasan",startDate:"2025-05-10",skills:S(20,25,29,32,32),intervention:"Selesai"},
  {id:"ST009",name:"Chong Jia En",year:2,className:"2 Bestari",subject:"Matematik",status:"Aktif",startDate:"2026-01-12",skills:S(7,10,14,18,22),intervention:"Tiada"},
  {id:"ST010",name:"Ahmad Rayyan",year:1,className:"1 Cekal",subject:"Bahasa Melayu",status:"Aktif",startDate:"2026-02-02",skills:S(3,5,5,6,11),intervention:"Perlu susulan"},
  {id:"ST011",name:"Izzah Humaira",year:3,className:"3 Amanah",subject:"Bahasa Melayu",status:"Aktif",startDate:"2025-03-03",skills:S(17,21,25,29,31),intervention:"Tiada"},
  {id:"ST012",name:"Harith Zikri",year:2,className:"2 Bijak",subject:"Bahasa Melayu",status:"Aktif",startDate:"2026-01-12",skills:S(6,8,11,15,19),intervention:"Tiada"},
];
const initialInterventions:Intervention[]=[
  {id:"IV001",studentId:"ST001",issue:"Lemah membaca perkataan",action:"Latihan perkataan KVK menggunakan kad imbas dan padanan gambar.",method:"Kumpulan kecil",start:"2026-08-03",review:"2026-08-17",status:"Sedang dilaksanakan"},
  {id:"IV002",studentId:"ST002",issue:"Tidak mengingat kemahiran",action:"Bacaan berulang dan latih tubi perkataan KVKV.",method:"Bimbingan individu",start:"2026-07-20",review:"2026-08-10",status:"Intervensi lanjutan"},
  {id:"IV003",studentId:"ST003",issue:"Lemah menggabung suku kata",action:"Bina perkataan dengan kad suku kata berwarna.",method:"ABM manipulatif",start:"2026-08-01",review:"2026-08-15",status:"Sedang dilaksanakan"},
  {id:"IV004",studentId:"ST007",issue:"Keliru huruf",action:"Aktiviti diskriminasi visual dan multisensori huruf.",method:"Permainan",start:"2026-08-06",review:"2026-08-20",status:"Sedang dilaksanakan"},
];
const schools=[
  ["SK Semangar","JBA3012","Bandar",25,72,"Telah dihantar"],
  ["SK Sedili Kecil","JBA3038","Sedili",18,61,"Draf"],
  ["SK Teluk Ramunia","JBA3055","Tanjung Surat",31,68,"Telah dihantar"],
  ["SK Lok Heng","JBA3061","Lok Heng",22,55,"Belum mula"],
  ["SK Bandar Penawar 2","JBA3074","Bandar",27,79,"Disahkan"],
  ["SK Sungai Rengit","JBA3044","Tanjung Surat",19,64,"Draf"],
];
const appsScriptEndpoint=(process.env.NEXT_PUBLIC_GOOGLE_APPS_SCRIPT_URL||"https://script.google.com/macros/s/AKfycbxxplK0PDUs2sS0_CkVes8RB9c42dSX8ptP7ZMMXmGDJl1Nt_rO7fOMS99YN2SFChvY/exec").trim();
const localService=createLocalDataService<Student>("myHeadcountKT-demo-v1");
const appsScriptService=appsScriptEndpoint?createAppsScriptDataService<Student>(appsScriptEndpoint,(value)=>{
  const student=normalizeAppsScriptStudent(value);
  return {...student,skills:student.skills as Record<Cycle,number>};
}):null;
const kp=(v:number)=>v>=32?"Menguasai":`KP${v}`;
const initials=(n:string)=>n.split(" ").slice(0,2).map(p=>p[0]).join("");
const date=(d:string)=>new Intl.DateTimeFormat("ms-MY",{day:"numeric",month:"short",year:"numeric"}).format(new Date(d));
const range=(v:number)=>v<=5?"KP1–KP5":v<=12?"KP6–KP12":v<=19?"KP13–KP19":v<=27?"KP20–KP27":v<32?"KP28–KP32":"Menguasai";

const guruMenu=[
  ["dashboard","Dashboard",LayoutDashboard],["students","Murid Saya",Users],["headcount","Headcount",FileSpreadsheet],
  ["interventions","Intervensi",Activity],["analysis","Analisis",BarChart3],["reports","Laporan",FileBarChart],
] as const;
const adminMenu=[
  ["dashboard","Dashboard Daerah",LayoutDashboard],["schools","Sekolah",Building2],["headcount","Headcount",FileSpreadsheet],
  ["interventions","Intervensi",Activity],["submissions","Penghantaran",ClipboardCheck],["reports","Laporan",FileBarChart],
  ["users","Pengguna",UserCog],["settings","Tetapan",Settings],["audit","Audit",History],
] as const;

export default function HeadcountApp(){
  const [role,setRole]=useState<Role>("guru"),[view,setView]=useState<View>("dashboard"),[students,setStudents]=useState(seed);
  const [interventions,setInterventions]=useState(initialInterventions),[cycle,setCycle]=useState<Cycle>("AR 3"),[subject,setSubject]=useState<Subject|"Semua">("Bahasa Melayu");
  const [year,setYear]=useState("Semua tahun"),[query,setQuery]=useState(""),[selected,setSelected]=useState<Student|null>(null),[modal,setModal]=useState<"add"|"intervention"|"submit"|null>(null);
  const [mobile,setMobile]=useState(false),[toast,setToast]=useState(""),[saved,setSaved]=useState("Disimpan 9:42 pagi"),[undo,setUndo]=useState<Student[]|null>(null);
  const [submission,setSubmission]=useState<Record<string,string>>({TOV:"Disahkan Admin","AR 1":"Disahkan Admin","AR 2":"Telah Dihantar","AR 3":"Draf"});
  const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
  const announce=(m:string)=>{setToast(m);if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(()=>setToast(""),3600)};
  useEffect(()=>{
    let active=true;
    const load=async()=>{
      if(!appsScriptService){
        const cached=await localService.getStudents();
        if(active&&cached.length)setStudents(cached);
        if(active)setSaved("Mod demo lokal · endpoint belum dikonfigurasi");
        return;
      }
      try{
        const remote=await appsScriptService.getStudents();
        if(!active)return;
        if(remote.length){setStudents(remote);await localService.saveStudents(remote)}
        setSaved("Google Sheets disambungkan");
      }catch(error){
        const cached=await localService.getStudents();
        if(!active)return;
        if(cached.length)setStudents(cached);
        setSaved("Mod demo lokal · Google Sheets gagal");
        announce(`Google Sheets tidak dapat dicapai. Data demo lokal digunakan. ${error instanceof Error?error.message:""}`.trim());
      }
    };
    void load();
    return()=>{active=false};
  },[]);
  const persist=(next:Student[],previous?:Student[])=>{if(previous)setUndo(previous);setStudents(next);localService.saveStudents(next).catch(()=>announce("Cache lokal tidak dapat disimpan."));setSaved(`Disimpan lokal ${new Intl.DateTimeFormat("ms-MY",{hour:"numeric",minute:"2-digit"}).format(new Date())}`)};
  const filtered=useMemo(()=>students.filter(s=>(subject==="Semua"||s.subject===subject)&&(year==="Semua tahun"||s.year===Number(year.slice(-1)))&&s.name.toLowerCase().includes(query.toLowerCase())),[students,subject,year,query]);
  const menu=role==="guru"?guruMenu:adminMenu;
  const go=(v:View)=>{setView(v);setMobile(false);window.scrollTo({top:0,behavior:"smooth"})};
  const updateSkill=async(id:string,value:number)=>{
    const student=students.find(s=>s.id===id);
    const prev=students;
    persist(students.map(s=>s.id===id?{...s,skills:{...s.skills,[cycle]:value}}:s),prev);
    if(!appsScriptService||!student)return;
    try{
      await appsScriptService.saveAssessment(id,cycle,`KP${value}`,{subject:student.subject,tahun_data:2026});
      setSaved(`Google Sheets · ${new Intl.DateTimeFormat("ms-MY",{hour:"numeric",minute:"2-digit"}).format(new Date())}`);
    }catch(error){
      setSaved("Disimpan lokal · Google Sheets gagal");
      announce(`Penilaian disimpan pada peranti sahaja. ${error instanceof Error?error.message:""}`.trim());
    }
  };
  const saveIntervention=async(i:Intervention)=>{
    setInterventions(current=>[i,...current]);setModal(null);setSelected(null);
    if(!appsScriptService){announce("Intervensi disimpan dalam mod demo lokal.");return}
    const student=students.find(s=>s.id===i.studentId);
    try{
      await appsScriptService.saveIntervention({studentId:i.studentId,skillCode:`KP${student?.skills["AR 3"]??1}`,issue:i.issue,action:i.action,method:i.method,startDate:i.start,reviewDate:i.review,status:i.status});
      announce("Intervensi berjaya disimpan ke Google Sheets.");
    }catch(error){
      announce(`Intervensi disimpan pada peranti sahaja. ${error instanceof Error?error.message:""}`.trim());
    }
  };
  const saveStudent=async(student:Student)=>{
    persist([...students,student],students);setModal(null);
    if(!appsScriptService){announce("Murid disimpan dalam mod demo lokal.");return}
    try{
      await appsScriptService.saveStudent({studentId:student.id,name:student.name,year:student.year,className:student.className,subject:student.subject,status:student.status,startDate:student.startDate});
      announce("Murid baharu berjaya disimpan ke Google Sheets.");
    }catch(error){
      announce(`Murid disimpan pada peranti sahaja. ${error instanceof Error?error.message:""}`.trim());
    }
  };
  const submitCurrentCycle=async()=>{
    if(!appsScriptService){setSubmission(current=>({...current,[cycle]:"Telah Dihantar"}));setModal(null);announce(`Data ${cycle} ditanda dihantar dalam mod demo lokal.`);return}
    try{
      await appsScriptService.submitCycle(cycle,{subject:subject==="Semua"?"Bahasa Melayu":subject,tahun:2026});
      setSubmission(current=>({...current,[cycle]:"Telah Dihantar"}));setModal(null);announce(`Data ${cycle} telah dihantar dan direkodkan dalam Google Sheets.`);
    }catch(error){
      setModal(null);announce(`Penghantaran gagal; data kekal sebagai draf. ${error instanceof Error?error.message:""}`.trim());
    }
  };
  const exportCsv=()=>{const rows=[["ID","Nama","Tahun","Kelas","Subjek",...cycles],...filtered.map(s=>[s.id,s.name,s.year,s.className,s.subject,...cycles.map(c=>kp(s.skills[c]))])];const csv=rows.map(r=>r.map(x=>`"${x}"`).join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff",csv],{type:"text/csv"}));a.download=`headcount-${cycle.replace(" ","-")}.csv`;a.click();URL.revokeObjectURL(a.href);announce("Fail CSV telah dijana.")};
  const props={students:filtered,allStudents:students,cycle,setCycle,subject,setSubject,year,setYear,query,setQuery,go,setSelected,announce,exportCsv};
  return <div className="app-shell">
    <aside className={`sidebar ${mobile?"open":""}`}>
      <div className="brand"><b><GraduationCap size={23}/></b><span><strong>myHeadcountKT</strong><small>Headcount & Intervensi</small></span><button onClick={()=>setMobile(false)}><X size={20}/></button></div>
      <div className="school-card"><i><School size={20}/></i><span><small>{role==="guru"?"Sekolah anda":"Pentadbir sistem"}</small><strong>{role==="guru"?"SK Semangar":"PPD Kota Tinggi"}</strong><em>{role==="guru"?"JBA3012 · Zon Bandar":"Johor"}</em></span></div>
      <nav><p>MENU UTAMA</p>{menu.map(([key,label,Icon])=><button key={key} className={view===key?"active":""} onClick={()=>go(key)}><Icon size={19}/><span>{label}</span>{key==="interventions"&&<em>{role==="guru"?4:18}</em>}</button>)}</nav>
      <div className="side-bottom"><button onClick={()=>go("settings")}><Settings size={19}/>Profil & Tetapan</button><button><HelpCircle size={19}/>Bantuan</button><div><b className="avatar">{role==="guru"?"NA":"AD"}</b><span><strong>{role==="guru"?"Nur Aina":"Admin PPD"}</strong><small>{role==="guru"?"Guru Pemulihan Khas":"Pentadbir Daerah"}</small></span><LogOut size={17}/></div></div>
    </aside>{mobile&&<button className="backdrop nav" onClick={()=>setMobile(false)}/>}
    <main><header className="topbar"><div><button className="menu-btn" onClick={()=>setMobile(true)}><Menu size={21}/></button><span><small>{role==="guru"?"PORTAL GURU":"PORTAL ADMIN"}</small><strong>{menu.find(x=>x[0]===view)?.[1]||"Tetapan"}</strong></span></div><div><span className="role-toggle"><button className={role==="guru"?"active":""} onClick={()=>{setRole("guru");go("dashboard")}}>Guru</button><button className={role==="admin"?"active":""} onClick={()=>{setRole("admin");go("dashboard")}}>Admin</button></span><button className="bell"><Bell size={20}/><i/></button><button className="profile"><b className="avatar">{role==="guru"?"NA":"AD"}</b><span>{role==="guru"?"Cikgu Aina":"Admin Daerah"}</span><ChevronDown size={15}/></button></div></header>
      <div className="page">
        {role==="guru"?<>
          {view==="dashboard"&&<GuruDashboard {...props}/>} {view==="students"&&<StudentsView {...props} onAdd={()=>setModal("add")} onIntervention={(s:Student)=>{setSelected(s);setModal("intervention")}}/>}
          {view==="headcount"&&<Headcount {...props} saved={saved} updateSkill={updateSkill} undo={()=>{if(undo){const now=students;persist(undo);setUndo(now);announce("Perubahan terakhir dibatalkan.")}}} canUndo={!!undo} submission={submission} onSubmit={()=>setModal("submit")}/>} 
          {view==="interventions"&&<Interventions students={students} interventions={interventions} setSelected={setSelected} onAdd={()=>setModal("intervention")}/>} {view==="analysis"&&<Analysis students={students}/>} {view==="reports"&&<Reports role={role} exportCsv={exportCsv} announce={announce}/>} {view==="settings"&&<SettingsView reset={()=>{persist(seed,students);announce("Data demo dipulihkan.")}}/>}
        </>:<>
          {view==="dashboard"&&<AdminDashboard go={go}/>} {view==="schools"&&<SchoolsView/>} {view==="headcount"&&<AdminHeadcount/>} {view==="interventions"&&<AdminInterventions/>} {view==="submissions"&&<Submissions announce={announce}/>} {view==="reports"&&<Reports role={role} exportCsv={exportCsv} announce={announce}/>} {view==="users"&&<UsersView/>} {view==="audit"&&<Audit/>} {view==="settings"&&<SettingsView reset={()=>{persist(seed,students);announce("Data demo dipulihkan.")}}/>}
        </>}
      </div>
    </main>
    {selected&&!modal&&<StudentDrawer student={selected} close={()=>setSelected(null)} intervention={()=>setModal("intervention")}/>} 
    {modal==="add"&&<AddModal close={()=>setModal(null)} save={s=>{void saveStudent(s)}}/>}
    {modal==="intervention"&&<InterventionModal students={students} selected={selected} close={()=>{setModal(null);setSelected(null)}} save={i=>{void saveIntervention(i)}}/>}
    {modal==="submit"&&<Confirm cycle={cycle} close={()=>setModal(null)} confirm={()=>{void submitCurrentCycle()}}/>}
    {toast&&<div className="toast"><CheckCircle2 size={19}/>{toast}</div>}
  </div>
}

function Heading({eyebrow,title,desc,children}:{eyebrow:string;title:string;desc:string;children?:React.ReactNode}){return <section className="heading"><div><span>{eyebrow}</span><h1>{title}</h1><p>{desc}</p></div>{children}</section>}
function CardHeader({title,desc,children}:{title:string;desc?:string;children?:React.ReactNode}){return <div className="card-header"><div><h2>{title}</h2>{desc&&<p>{desc}</p>}</div>{children}</div>}
function Status({text}:{text:string}){const t=text.toLowerCase();const tone=t.includes("berjaya")||t.includes("disahkan")||t.includes("meningkat")||t==="aktif"?"green":t.includes("lewat")||t.includes("susulan")||t.includes("segera")?"red":t.includes("draf")||t.includes("perhatian")?"amber":t.includes("intervensi")||t.includes("dihantar")?"blue":"gray";return <span className={`status ${tone}`}><i/>{text}</span>}
function Stat({label,value,detail,Icon,tone}:{label:string;value:number|string;detail:string;Icon:typeof Users;tone:string}){return <div className="stat"><i className={tone}><Icon size={21}/></i><span><small>{label}</small><strong>{value}</strong><em>{detail}</em></span></div>}
function StudentCell({s,onClick}:{s:Student;onClick?:()=>void}){return <button className="student-cell" onClick={onClick}><b>{initials(s.name)}</b><span><strong>{s.name}</strong><small>{s.id}</small></span></button>}
function Delta({n}:{n:number}){return <span className={`delta ${n>0?"up":n<0?"down":"same"}`}>{n>0?<TrendingUp size={15}/>:n<0?<TrendingDown size={15}/>:<ArrowRight size={15}/>} {n>0?`+${n} KP`:n===0?"Kekal":`${n} KP`}</span>}
function LineChart(){return <div className="line-chart"><div className="chart-grid"><i/><i/><i/><i/></div><div className="line"><i/><i/><i/><i/><i/></div><div className="line-labels"><span>TOV</span><span>AR 1</span><span>AR 2</span><span>AR 3</span><span>Semasa</span></div></div>}

type CommonProps={students:Student[];allStudents:Student[];cycle:Cycle;setCycle:(v:Cycle)=>void;subject:Subject|"Semua";setSubject:(v:Subject|"Semua")=>void;year:string;setYear:(v:string)=>void;query:string;setQuery:(v:string)=>void;go:(v:View)=>void;setSelected:(s:Student|null)=>void;announce:(m:string)=>void;exportCsv:()=>void};

function GuruDashboard(p:CommonProps){
  const scope=p.students.length?p.students:p.allStudents,stats={total:scope.length,up:scope.filter(s=>s.skills[p.cycle]>s.skills.TOV).length,same:scope.filter(s=>s.skills[p.cycle]===s.skills.TOV).length,intervention:scope.filter(s=>s.intervention==="Aktif"||s.intervention==="Perlu susulan").length,master:scope.filter(s=>s.skills[p.cycle]>=32||s.status==="Pelepasan").length};
  const labels=["KP1–KP5","KP6–KP12","KP13–KP19","KP20–KP27","KP28–KP32","Menguasai"],values=labels.map(l=>scope.filter(s=>range(s.skills[p.cycle])===l).length),max=Math.max(...values,1);
  const attention=p.allStudents.filter(s=>s.intervention==="Aktif"||s.intervention==="Perlu susulan"||s.skills["AR 3"]<=s.skills["AR 2"]).slice(0,5);
  return <>
    <Heading eyebrow="KHAMIS, 13 OGOS 2026" title="Selamat datang, Cikgu Aina." desc="Ini ringkasan perkembangan murid Pemulihan Khas anda."><button className="primary" onClick={()=>p.go("headcount")}><FileSpreadsheet size={18}/> Rekod Headcount</button></Heading>
    <section className="action-strip"><div><i><AlertCircle size={20}/></i><span><strong>Perlu tindakan hari ini</strong><small>3 perkara memerlukan perhatian anda</small></span></div><nav><button onClick={()=>p.go("interventions")}><i className="red"/>2 intervensi lewat disemak<ChevronRight size={17}/></button><button onClick={()=>p.go("headcount")}><i className="blue"/>AR 3 masih dalam draf<ChevronRight size={17}/></button><button onClick={()=>p.go("students")}><i className="amber"/>3 murid tiada perkembangan<ChevronRight size={17}/></button></nav></section>
    <section className="filters"><label className="search"><Search size={17}/><input value={p.query} onChange={e=>p.setQuery(e.target.value)} placeholder="Cari nama murid"/></label><label><span>Tahun data</span><select><option>2026</option><option>2027</option></select></label><label><span>Mata pelajaran</span><select value={p.subject} onChange={e=>p.setSubject(e.target.value as Subject|"Semua")}><option>Bahasa Melayu</option><option>Matematik</option><option>Semua</option></select></label><label><span>Tahun murid</span><select value={p.year} onChange={e=>p.setYear(e.target.value)}><option>Semua tahun</option><option>Tahun 1</option><option>Tahun 2</option><option>Tahun 3</option></select></label><label><span>Tempoh</span><select value={p.cycle} onChange={e=>p.setCycle(e.target.value as Cycle)}>{["TOV","AR 1","AR 2","AR 3"].map(x=><option key={x}>{x}</option>)}</select></label><button className="outline"><Filter size={17}/>Penapis <b>3</b></button></section>
    <section className="stat-grid"><Stat label="Jumlah Murid" value={stats.total} detail="Murid aktif" Icon={Users} tone="blue"/><Stat label="Meningkat" value={stats.up} detail={`${stats.total?Math.round(stats.up/stats.total*100):0}% daripada murid`} Icon={TrendingUp} tone="green"/><Stat label="Tidak Berubah" value={stats.same} detail="Perlu perhatian" Icon={ArrowRight} tone="amber"/><Stat label="Perlu Intervensi" value={stats.intervention} detail="2 lewat semakan" Icon={Activity} tone="red"/><Stat label="Menguasai" value={stats.master} detail="Layak pelepasan" Icon={Award} tone="purple"/></section>
    <section className="dashboard-grid">
      <article className="card distribution"><CardHeader title="Kedudukan Semasa Murid" desc={`Taburan kemahiran bagi ${p.cycle}`}><button className="text-btn" onClick={()=>p.go("analysis")}>Lihat analisis <ArrowRight size={15}/></button></CardHeader><div className="bars">{values.map((v,i)=><div key={labels[i]}><b>{v}</b><span><i style={{height:`${Math.max(v/max*100,v?12:2)}%`}}/></span><small>{labels[i]}</small></div>)}</div><footer><span><i/> {scope.length} murid dianalisis</span><span>Kemas kini terakhir: Hari ini, 9:42 pagi</span></footer></article>
      <article className="card progress"><CardHeader title="Perkembangan Headcount" desc="Purata kemahiran murid"><button className="icon"><MoreHorizontal size={19}/></button></CardHeader><div className="metric"><span><small>Purata semasa</small><strong>KP12.4</strong></span><em><TrendingUp size={14}/>+4.6 KP</em></div><LineChart/><footer><span><strong>18</strong><small>Meningkat</small></span><span><strong>5</strong><small>Kekal</small></span><span><strong>7</strong><small>Capai ETR</small></span></footer></article>
      <article className="card intervention-chart"><CardHeader title="Status Intervensi" desc="Kes aktif dan selesai"/><div><div className="donut"><span><strong>9</strong><small>Jumlah</small></span></div><ul><li><i className="blue"/>Sedang intervensi <b>4</b></li><li><i className="green"/>Berjaya <b>3</b></li><li><i className="gray"/>Selesai <b>1</b></li><li><i className="red"/>Perlu susulan <b>1</b></li></ul></div><button className="card-link" onClick={()=>p.go("interventions")}>Urus semua intervensi <ArrowRight size={15}/></button></article>
    </section>
    <section className="card table-card"><CardHeader title="Murid Perlu Tindakan" desc="Disusun mengikut tahap keutamaan"><button className="text-btn" onClick={()=>p.go("students")}>Lihat semua murid <ArrowRight size={15}/></button></CardHeader><Table><thead><tr><th>MURID</th><th>KELAS</th><th>TOV</th><th>{p.cycle}</th><th>PERUBAHAN</th><th>STATUS</th><th/></tr></thead><tbody>{attention.map(s=><tr key={s.id}><td><StudentCell s={s} onClick={()=>p.setSelected(s)}/></td><td>{s.className}</td><td><b className="kp neutral">{kp(s.skills.TOV)}</b></td><td><b className="kp">{kp(s.skills[p.cycle])}</b></td><td><Delta n={s.skills[p.cycle]-s.skills.TOV}/></td><td><Status text={s.intervention==="Perlu susulan"?"Segera":s.intervention==="Aktif"?"Intervensi aktif":"Perlu perhatian"}/></td><td><button className="icon" onClick={()=>p.setSelected(s)}><ChevronRight size={18}/></button></td></tr>)}</tbody></Table></section>
  </>
}

function Table({children}:{children:React.ReactNode}){return <div className="table-wrap"><table>{children}</table></div>}
function Toolbar({query,setQuery,children}:{query?:string;setQuery?:(v:string)=>void;children?:React.ReactNode}){return <div className="toolbar"><label className="search"><Search size={17}/><input value={query} onChange={e=>setQuery?.(e.target.value)} placeholder="Cari nama, ID atau sekolah"/></label>{children}</div>}

function StudentsView(p:CommonProps&{onAdd:()=>void;onIntervention:(s:Student)=>void}){return <>
  <Heading eyebrow="PENGURUSAN MURID" title="Murid Saya" desc="Urus profil, rekod penilaian dan perkembangan murid."><div className="heading-actions"><button className="outline" onClick={p.exportCsv}><Download size={17}/>Eksport</button><button className="primary" onClick={p.onAdd}><Plus size={18}/>Tambah Murid</button></div></Heading>
  <section className="card table-card"><Toolbar query={p.query} setQuery={p.setQuery}><select value={p.year} onChange={e=>p.setYear(e.target.value)}><option>Semua tahun</option><option>Tahun 1</option><option>Tahun 2</option><option>Tahun 3</option></select><select value={p.subject} onChange={e=>p.setSubject(e.target.value as Subject|"Semua")}><option>Semua</option><option>Bahasa Melayu</option><option>Matematik</option></select><button className="outline"><Upload size={16}/>Import CSV / Excel</button></Toolbar><div className="table-meta"><span><strong>{p.students.length}</strong> murid ditemui</span><button><Download size={15}/>Muat turun template</button></div><Table><thead><tr><th>MURID</th><th>TAHUN / KELAS</th><th>SUBJEK</th><th>TOV</th><th>AR 1</th><th>AR 2</th><th>AR 3</th><th>ETR</th><th>INTERVENSI</th><th/></tr></thead><tbody>{p.students.map(s=><tr key={s.id}><td><StudentCell s={s} onClick={()=>p.setSelected(s)}/></td><td><strong>Tahun {s.year}</strong><small className="sub">{s.className}</small></td><td><b className="subject">{s.subject==="Bahasa Melayu"?"BM":"MT"}</b></td>{(["TOV","AR 1","AR 2","AR 3","ETR"] as Cycle[]).map(c=><td key={c}><b className={`kp ${c==="TOV"?"neutral":c==="ETR"?"target":""}`}>{kp(s.skills[c])}</b></td>)}<td><Status text={s.intervention}/></td><td><div className="row-actions"><button onClick={()=>p.onIntervention(s)}><Plus size={17}/></button><button onClick={()=>p.setSelected(s)}><ChevronRight size={18}/></button></div></td></tr>)}</tbody></Table><div className="pagination"><span>Menunjukkan 1–{p.students.length} daripada {p.students.length}</span><div><button disabled><ChevronLeft size={17}/></button><button className="active">1</button><button disabled><ChevronRight size={17}/></button></div></div></section>
  </>}

function Headcount(p:CommonProps&{saved:string;updateSkill:(id:string,v:number)=>void;undo:()=>void;canUndo:boolean;submission:Record<string,string>;onSubmit:()=>void}){
  const state=p.submission[p.cycle]||"Belum Mula",locked=state==="Dikunci"||state==="Disahkan Admin";
  return <><Heading eyebrow="REKOD PENILAIAN" title="Headcount Murid" desc="Kemas kini kemahiran murid dengan pantas. Setiap perubahan disimpan automatik."><div className="heading-actions"><span className="saved"><Check size={15}/>{p.saved}</span><button className="outline" disabled={!p.canUndo} onClick={p.undo}><RotateCcw size={16}/>Undo</button><button className="primary" disabled={locked} onClick={p.onSubmit}><Upload size={17}/>Hantar Data</button></div></Heading>
    <section className="card headcount-top"><div><i><BookOpen size={21}/></i><label><small>Mata pelajaran</small><select value={p.subject} onChange={e=>p.setSubject(e.target.value as Subject|"Semua")}><option>Bahasa Melayu</option><option>Matematik</option></select></label></div><span><small>Status {p.cycle}</small><Status text={state}/>{locked&&<Lock size={15}/>}</span></section>
    <div className="cycle-tabs">{cycles.map(c=><button key={c} className={c===p.cycle?"active":""} onClick={()=>p.setCycle(c)}>{c}{p.submission[c]==="Disahkan Admin"?<CheckCircle2 size={14}/>:p.submission[c]==="Draf"?<i/>:null}</button>)}</div>
    {locked&&<div className="locked"><Lock size={18}/><span><strong>Data {p.cycle} telah disahkan dan dikunci</strong><small>Hubungi admin daerah jika perubahan diperlukan.</small></span></div>}
    <section className="card sheet"><CardHeader title={`${p.cycle} · ${p.subject}`} desc={`${p.students.length} murid · Tahun data 2026`}><div><button className="outline"><WandSparkles size={16}/>Bulk Update</button><button className="outline" onClick={p.exportCsv}><Download size={16}/>Eksport</button></div></CardHeader><Table><thead><tr><th>#</th><th>NAMA MURID</th><th>KELAS</th><th>KEMAHIRAN {p.cycle}</th><th>KATEGORI</th><th>PERUBAHAN DARI TOV</th><th>STATUS</th></tr></thead><tbody>{p.students.map((s,i)=>{const d=s.skills[p.cycle]-s.skills.TOV;return <tr key={s.id}><td>{String(i+1).padStart(2,"0")}</td><td><StudentCell s={s}/></td><td>{s.className}</td><td><label className={`skill-select ${locked?"disabled":""}`}><select value={s.skills[p.cycle]} disabled={locked} onChange={e=>p.updateSkill(s.id,Number(e.target.value))}>{skillOptions.map(v=><option key={v} value={v}>{kp(v)}</option>)}</select><ChevronDown size={15}/></label></td><td><span className="range">{range(s.skills[p.cycle])}</span></td><td><Delta n={d}/></td><td>{s.skills[p.cycle]>=s.skills.ETR?<Status text="Capai ETR"/>:d===0?<Status text="Perlu perhatian"/>:<Status text="Meningkat"/>}</td></tr>})}</tbody></Table><footer className="autosave"><span><CheckCircle2 size={16}/>Semua perubahan telah disimpan</span><span>Simpan Draf aktif secara automatik</span></footer></section>
  </>}

function Interventions({students,interventions,setSelected,onAdd}:{students:Student[];interventions:Intervention[];setSelected:(s:Student)=>void;onAdd:()=>void}){return <><Heading eyebrow="TINDAKAN SUSULAN" title="Intervensi" desc="Rancang, laksana dan nilai intervensi murid secara berstruktur."><button className="primary" onClick={onAdd}><Plus size={18}/>Rekod Intervensi</button></Heading><section className="stat-grid four"><Stat label="Sedang Dilaksana" value={4} detail="Intervensi aktif" Icon={Activity} tone="blue"/><Stat label="Perlu Disemak" value={2} detail="Minggu ini" Icon={Clock3} tone="amber"/><Stat label="Berjaya" value={3} detail="Sasaran dicapai" Icon={CheckCircle2} tone="green"/><Stat label="Perlu Susulan" value={1} detail="Strategi baharu" Icon={AlertCircle} tone="red"/></section><section className="card intervention-list"><Toolbar><button className="outline"><Filter size={16}/>Semua status</button><button className="outline"><CalendarDays size={16}/>Tarikh semakan</button></Toolbar>{interventions.map(item=>{const s=students.find(x=>x.id===item.studentId)!;const overdue=new Date(item.review)<new Date("2026-08-13");return <article key={item.id} className={overdue?"urgent":""}><i/><StudentCell s={s} onClick={()=>setSelected(s)}/><div><small>ISU DIKENAL PASTI</small><strong>{item.issue}</strong><p>{item.action}</p></div><div><small>KAEDAH</small><strong>{item.method}</strong><em>Mula {date(item.start)}</em></div><div className={overdue?"overdue":""}><small>TARIKH SEMAKAN</small><strong><CalendarDays size={15}/>{date(item.review)}</strong>{overdue&&<em>Lewat disemak</em>}</div><div><Status text={item.status==="Sedang dilaksanakan"?"Intervensi aktif":item.status}/><button className="outline small">Semak <ChevronRight size={15}/></button></div></article>})}</section></>}

function Analysis({students}:{students:Student[]}){const vals=[students.filter(s=>s.skills["AR 3"]<=5).length,students.filter(s=>s.skills["AR 3"]>=6&&s.skills["AR 3"]<=12).length,students.filter(s=>s.skills["AR 3"]>=13&&s.skills["AR 3"]<=19).length,students.filter(s=>s.skills["AR 3"]>=20&&s.skills["AR 3"]<=27).length,students.filter(s=>s.skills["AR 3"]>=28).length];return <><Heading eyebrow="CERAPAN DATA" title="Analisis Sekolah" desc="Kenal pasti pola perkembangan dan jurang kemahiran murid."><button className="outline"><Download size={17}/>Eksport Analisis</button></Heading><section className="analysis-grid"><article className="card big-analysis"><CardHeader title="Pergerakan Kemahiran" desc="Purata KP bagi setiap tempoh penilaian"/><div className="metric"><span><small>Peningkatan purata</small><strong>+7.3 KP</strong></span><em><TrendingUp size={14}/>18 murid meningkat</em></div><LineChart/></article><article className="card etr"><CardHeader title="Pencapaian ETR" desc="Status sasaran individu"/><div className="etr-ring"><span><strong>68%</strong><small>Capai sasaran</small></span></div><ul><li><i className="green"/>Telah mencapai <b>17</b></li><li><i className="amber"/>Hampir mencapai <b>5</b></li><li><i className="red"/>Belum mencapai <b>3</b></li></ul></article></section><section className="card horizontal"><CardHeader title="Taburan Murid Mengikut Julat Kemahiran" desc="Perbandingan TOV dengan AR 3"/>{["KP1–KP5","KP6–KP12","KP13–KP19","KP20–KP27","KP28–KP32"].map((label,i)=><div key={label}><span>{label}</span><b><i style={{width:`${[50,72,42,26,12][i]}%`}}/><em style={{width:`${Math.max(vals[i]*15,8)}%`}}/></b><strong>{vals[i]}</strong></div>)}<footer><span><i/>TOV</span><span><i/>AR 3</span></footer></section></>}

function Reports({role,exportCsv,announce}:{role:Role;exportCsv:()=>void;announce:(m:string)=>void}){const items=role==="guru"?[["Laporan Headcount Sekolah","Ringkasan headcount mengikut tempoh dan kemahiran",FileSpreadsheet],["Perkembangan Murid","Perbandingan TOV, AR dan pencapaian ETR",TrendingUp],["Laporan Intervensi","Rekod intervensi, semakan dan hasil tindakan",Activity],["Profil Individu Murid","Laporan lengkap bagi seorang murid",UserRound]]:[["Laporan Headcount Daerah","Analisis keseluruhan sekolah dan zon",FileSpreadsheet],["Analisis Sekolah","Perbandingan prestasi antara sekolah",Building2],["Status Penghantaran","Pemantauan penghantaran setiap cycle",ClipboardCheck],["Analisis Intervensi","Keberkesanan intervensi peringkat daerah",Activity]];return <><Heading eyebrow="PUSAT LAPORAN" title="Laporan" desc="Jana, cetak dan eksport laporan berdasarkan data semasa."/><section className="report-grid">{items.map(([title,desc,Icon])=><article className="card report" key={title as string}><i><Icon size={23}/></i><div><h2>{title as string}</h2><p>{desc as string}</p></div><footer><button onClick={exportCsv}><FileSpreadsheet size={16}/>Excel</button><button onClick={()=>announce("Pratonton PDF disediakan untuk cetakan.")}><FileText size={16}/>PDF</button><button onClick={()=>window.print()}><Printer size={16}/>Cetak</button></footer></article>)}</section><section className="card recent"><CardHeader title="Laporan Terkini" desc="Sejarah laporan yang telah dijana"/><div><FileText size={19}/><span><strong>Laporan Headcount AR 2 · Bahasa Melayu</strong><small>Dijana pada 3 Ogos 2026, 11:20 pagi</small></span><Status text="Sedia"/><button className="icon"><Download size={17}/></button></div><div><FileSpreadsheet size={19}/><span><strong>Senarai Murid Mengikut Kemahiran</strong><small>Dijana pada 28 Julai 2026, 2:15 petang</small></span><Status text="Sedia"/><button className="icon"><Download size={17}/></button></div></section></>}

function AdminDashboard({go}:{go:(v:View)=>void}){return <><Heading eyebrow="KHAMIS, 13 OGOS 2026" title="Dashboard Daerah" desc="Pemantauan Pemulihan Khas · PPD Kota Tinggi"><button className="primary" onClick={()=>go("submissions")}><ClipboardCheck size={18}/>Status Penghantaran</button></Heading><AdminFilters/><section className="stat-grid admin"><Stat label="Jumlah Sekolah" value={42} detail="Semua sekolah aktif" Icon={Building2} tone="blue"/><Stat label="Telah Hantar" value={34} detail="81% sekolah" Icon={ClipboardCheck} tone="green"/><Stat label="Murid Pemulihan" value={864} detail="BM & Matematik" Icon={Users} tone="purple"/><Stat label="Murid Meningkat" value={621} detail="72% keseluruhan" Icon={TrendingUp} tone="green"/><Stat label="Menguasai" value={126} detail="15% murid" Icon={Award} tone="blue"/><Stat label="Perlu Intervensi" value={143} detail="17% murid" Icon={Activity} tone="red"/></section><section className="analysis-grid"><article className="card big-analysis"><CardHeader title="Pergerakan Headcount Daerah" desc="Purata perkembangan Bahasa Melayu"><button className="text-btn">Lihat terperinci <ArrowRight size={15}/></button></CardHeader><div className="metric"><span><small>Peningkatan keseluruhan</small><strong>+8.2 KP</strong></span><em><TrendingUp size={14}/>+14% dari AR 2</em></div><LineChart/></article><article className="card submission-chart"><CardHeader title="Status Penghantaran AR 3" desc="42 sekolah dalam daerah"/><div className="etr-ring"><span><strong>81%</strong><small>34 / 42</small></span></div><ul><li><i className="green"/>Telah dihantar <b>34</b></li><li><i className="amber"/>Dalam draf <b>5</b></li><li><i className="red"/>Belum mula <b>3</b></li></ul><button className="card-link" onClick={()=>go("submissions")}>Semak penghantaran <ArrowRight size={15}/></button></article></section><section className="card table-card"><CardHeader title="Sekolah Memerlukan Perhatian" desc="Berdasarkan penghantaran dan pencapaian semasa"><button className="text-btn" onClick={()=>go("schools")}>Lihat semua sekolah <ArrowRight size={15}/></button></CardHeader><Table><thead><tr><th>SEKOLAH</th><th>ZON</th><th>MURID</th><th>MENINGKAT</th><th>PERLU INTERVENSI</th><th>AR 3</th><th/></tr></thead><tbody>{schools.slice(1,5).map((s,i)=><tr key={s[1]}><td><SchoolCell row={s}/></td><td>{s[2]}</td><td>{s[3]}</td><td><span className="delta up"><TrendingUp size={15}/>{s[4]}%</span></td><td>{[5,7,4,3][i]} murid</td><td><Status text={s[5] as string}/></td><td><button className="icon"><ChevronRight size={18}/></button></td></tr>)}</tbody></Table></section></>}
function AdminFilters(){return <section className="admin-filters card"><label>Tahun<select><option>2026</option></select></label><label>Zon<select><option>Semua zon</option><option>Bandar</option><option>Sedili</option></select></label><label>Mata pelajaran<select><option>Bahasa Melayu</option><option>Matematik</option></select></label><label>Headcount<select><option>AR 3</option><option>AR 2</option></select></label><button className="outline"><Filter size={16}/>Lagi penapis</button></section>}
function SchoolCell({row}:{row:(string|number)[]}){return <div className="school-cell"><i><School size={18}/></i><span><strong>{row[0]}</strong><small>{row[1]}</small></span></div>}

function SchoolsView(){return <><Heading eyebrow="PENGURUSAN ORGANISASI" title="Sekolah" desc="Urus sekolah, zon dan guru yang berdaftar dalam sistem."><button className="primary"><Plus size={18}/>Tambah Sekolah</button></Heading><section className="card table-card"><Toolbar><button className="outline"><Filter size={16}/>Semua zon</button><button className="outline"><Download size={16}/>Eksport</button></Toolbar><Table><thead><tr><th>SEKOLAH</th><th>ZON</th><th>GURU</th><th>MURID</th><th>PENCAPAIAN</th><th>STATUS</th><th/></tr></thead><tbody>{schools.map(s=><tr key={s[1]}><td><SchoolCell row={s}/></td><td>{s[2]}</td><td>1 guru</td><td>{s[3]}</td><td><div className="progress-cell"><span><i style={{width:`${s[4]}%`}}/></span><b>{s[4]}%</b></div></td><td><Status text="Aktif"/></td><td><button className="icon"><MoreHorizontal size={18}/></button></td></tr>)}</tbody></Table></section></>}

function AdminHeadcount(){const heat=[[8,5,3,2,1,0],[5,7,4,2,0,0],[9,8,6,4,2,2],[6,7,4,3,1,1],[3,6,7,5,4,2],[5,5,4,3,2,0]];return <><Heading eyebrow="ANALISIS DAERAH" title="Headcount" desc="Taburan kemahiran murid mengikut sekolah dan zon."><button className="outline"><Download size={17}/>Eksport Data</button></Heading><AdminFilters/><section className="card heatmap-card"><CardHeader title="Taburan Kemahiran Mengikut Sekolah" desc="Warna lebih gelap menunjukkan bilangan murid lebih tinggi"/><div className="heat-wrap"><table><thead><tr><th>SEKOLAH</th><th>KP1–5</th><th>KP6–12</th><th>KP13–19</th><th>KP20–27</th><th>KP28–32</th><th>MENGUASAI</th></tr></thead><tbody>{schools.map((s,r)=><tr key={s[1]}><td><strong>{s[0]}</strong><small>{s[1]}</small></td>{heat[r].map((v,c)=><td key={c}><span data-level={Math.min(Math.ceil(v/2),4)}>{v}</span></td>)}</tr>)}</tbody></table></div><footer className="heat-legend"><span>Rendah</span><i data-level="1"/><i data-level="2"/><i data-level="3"/><i data-level="4"/><span>Tinggi</span></footer></section></>}

function AdminInterventions(){return <><Heading eyebrow="PEMANTAUAN DAERAH" title="Intervensi" desc="Analisis status dan keberkesanan intervensi semua sekolah."/><section className="stat-grid four"><Stat label="Intervensi Aktif" value={168} detail="42 sekolah" Icon={Activity} tone="blue"/><Stat label="Berjaya" value={94} detail="56% keberkesanan" Icon={CheckCircle2} tone="green"/><Stat label="Lewat Semakan" value={23} detail="Perlu tindakan guru" Icon={Clock3} tone="red"/><Stat label="Intervensi Lanjutan" value={31} detail="Strategi baharu" Icon={RotateCcw} tone="amber"/></section><section className="analysis-grid"><article className="card ranking"><CardHeader title="Kaedah Paling Berkesan" desc="Berdasarkan hasil intervensi"/>{[["Bimbingan individu",82],["Bacaan berulang",74],["ABM manipulatif",68],["Kumpulan kecil",61]].map(([n,v],i)=><div key={n as string}><b>{i+1}</b><span><strong>{n as string}</strong><i><em style={{width:`${v}%`}}/></i></span><small>{v}%</small></div>)}</article><article className="card intervention-chart admin"><CardHeader title="Status Keseluruhan" desc="Semua rekod tahun 2026"/><div><div className="donut"><span><strong>262</strong><small>Jumlah</small></span></div><ul><li><i className="blue"/>Aktif <b>168</b></li><li><i className="green"/>Berjaya <b>94</b></li><li><i className="amber"/>Lanjutan <b>31</b></li><li><i className="red"/>Lewat <b>23</b></li></ul></div></article></section></>}

function Submissions({announce}:{announce:(m:string)=>void}){const [verified,setVerified]=useState<string[]>(["JBA3074"]);return <><Heading eyebrow="PEMANTAUAN DATA" title="Status Penghantaran" desc="Semak, sahkan dan kunci penghantaran data sekolah."><button className="outline"><CalendarDays size={17}/>Tarikh Tutup: 21 Ogos</button></Heading><section className="submission-summary card"><div><strong>34</strong><small>Telah hantar</small></div><div><strong>5</strong><small>Dalam draf</small></div><div><strong>3</strong><small>Belum mula</small></div><div><strong>19</strong><small>Telah disahkan</small></div></section><section className="card table-card"><Toolbar><button className="outline"><Filter size={16}/>Semua status</button><button className="outline"><Download size={16}/>Eksport</button></Toolbar><Table><thead><tr><th>SEKOLAH</th><th>TOV</th><th>AR 1</th><th>AR 2</th><th>AR 3</th><th>KEMAS KINI</th><th>TINDAKAN</th></tr></thead><tbody>{schools.map((s,i)=>{const done=verified.includes(s[1] as string);return <tr key={s[1]}><td><SchoolCell row={s}/></td><td><Status text="Disahkan"/></td><td><Status text={i>4?"Telah dihantar":"Disahkan"}/></td><td><Status text={i===3?"Draf":"Telah dihantar"}/></td><td><Status text={done?"Disahkan":s[5] as string}/></td><td><small>12 Ogos 2026<br/>4:32 petang</small></td><td>{done?<button className="outline small"><Lock size={15}/>Dikunci</button>:<button className="primary small" onClick={()=>{setVerified([...verified,s[1] as string]);announce(`${s[0]} telah disahkan dan dikunci.`)}}><ShieldCheck size={15}/>Sahkan</button>}</td></tr>})}</tbody></Table></section></>}

function UsersView(){const data=[["Nur Aina Binti Ahmad","aina@moe-dl.edu.my","SK Semangar","Guru"],["Farah Nabila","farah@moe-dl.edu.my","SK Sedili Kecil","Guru"],["Mohd Azlan","azlan@moe-dl.edu.my","PPD Kota Tinggi","Admin"],["Siti Rafidah","rafidah@moe-dl.edu.my","SK Teluk Ramunia","Guru"]];return <><Heading eyebrow="AKSES SISTEM" title="Pengguna" desc="Urus akaun, peranan dan sekolah bagi setiap pengguna."><button className="primary"><Plus size={18}/>Tambah Pengguna</button></Heading><section className="card table-card"><Toolbar><button className="outline"><Filter size={16}/>Semua peranan</button></Toolbar><Table><thead><tr><th>PENGGUNA</th><th>E-MEL</th><th>SEKOLAH / ORGANISASI</th><th>PERANAN</th><th>STATUS</th><th/></tr></thead><tbody>{data.map(([name,email,school,userRole])=><tr key={email}><td><div className="student-cell"><b>{initials(name)}</b><span><strong>{name}</strong><small>Log masuk 2 hari lalu</small></span></div></td><td>{email}</td><td>{school}</td><td><span className="role-badge">{userRole==="Admin"?<ShieldCheck size={14}/>:<UserRound size={14}/>} {userRole}</span></td><td><Status text="Aktif"/></td><td><button className="icon"><MoreHorizontal size={18}/></button></td></tr>)}</tbody></Table></section></>}

function Audit(){const data=[["Mohd Azlan","Mengesahkan penghantaran AR 3","SK Bandar Penawar 2","Hari ini, 10:34 pagi"],["Nur Aina","Mengemas kini kemahiran murid","ST001 · KP9 → KP10","Hari ini, 9:42 pagi"],["Siti Rafidah","Menghantar data AR 3","SK Teluk Ramunia","Semalam, 4:32 petang"],["Mohd Azlan","Membuka semula cycle AR 2","SK Sedili Kecil","11 Ogos, 2:05 petang"]];return <><Heading eyebrow="JEJAK SISTEM" title="Audit Log" desc="Rekod semua perubahan dan tindakan penting dalam sistem."><button className="outline"><Download size={17}/>Eksport Log</button></Heading><section className="card audit"><Toolbar><button className="outline"><CalendarDays size={16}/>30 hari terakhir</button></Toolbar>{data.map(([user,action,context,time],i)=><article key={time}><i className={`a${i}`}><History size={17}/></i><span><strong>{action}</strong><p><b>{user}</b> · {context}</p></span><small>{time}</small><button className="icon"><ChevronRight size={17}/></button></article>)}</section></>}

function SettingsView({reset}:{reset:()=>void}){return <><Heading eyebrow="KONFIGURASI" title="Profil & Tetapan" desc="Urus profil, pilihan sistem dan data demo."/><section className="settings-grid"><article className="card profile-settings"><b>NA</b><span><h2>Nur Aina Binti Ahmad</h2><p>Guru Pemulihan Khas</p><small>aina@moe-dl.edu.my</small></span><button className="outline">Kemaskini Profil</button></article><article className="card settings-list"><h2>Tetapan Sistem</h2><div><span><Bell size={19}/><i><strong>Notifikasi tarikh semakan</strong><small>Terima peringatan intervensi yang perlu disemak</small></i></span><label className="switch"><input type="checkbox" defaultChecked/><i/></label></div><div><span><CheckCircle2 size={19}/><i><strong>Autosave</strong><small>Simpan perubahan penilaian secara automatik</small></i></span><label className="switch"><input type="checkbox" defaultChecked/><i/></label></div><div><span><CalendarDays size={19}/><i><strong>Tahun data aktif</strong><small>Tahun semasa bagi paparan sistem</small></i></span><select><option>2026</option><option>2027</option></select></div></article><article className="card danger"><div><RotateCcw size={20}/><span><strong>Pulihkan data demo</strong><p>Kembalikan semua data murid kepada keadaan asal prototaip.</p></span></div><button className="outline" onClick={reset}>Pulihkan Data</button></article></section></>}

function StudentDrawer({student,close,intervention}:{student:Student;close:()=>void;intervention:()=>void}){return <div className="layer drawer-layer"><button className="backdrop" onClick={close}/><aside className="drawer"><header><span><small>PROFIL MURID</small><h2>{student.name}</h2><p>Tahun {student.year} · {student.className}</p></span><button className="icon" onClick={close}><X size={20}/></button></header><main><section className="profile-hero"><b>{initials(student.name)}</b><span><Status text={student.status}/><p>{student.id} · {student.subject}</p><small>Mula Pemulihan: {date(student.startDate)}</small></span></section><section><Title title="Perkembangan Headcount" desc="Kemajuan kemahiran sepanjang 2026"><Delta n={student.skills["AR 3"]-student.skills.TOV}/></Title><div className="student-timeline">{(["TOV","AR 1","AR 2","AR 3","ETR"] as Cycle[]).map((c,i)=><div key={c} className={c==="ETR"?"target":""}><small>{c}</small><strong>{kp(student.skills[c])}</strong>{i<4&&<ArrowRight size={16}/>}</div>)}</div></section><section><Title title="Status Semasa" desc="Penilaian AR 3"/><div className="profile-stats"><div><small>Kemahiran</small><strong>{kp(student.skills["AR 3"])}</strong></div><div><small>Sasaran ETR</small><strong>{kp(student.skills.ETR)}</strong></div><div><small>Intervensi</small><Status text={student.intervention}/></div></div></section><section><Title title="Timeline Intervensi" desc="Hubungan intervensi dengan pencapaian"/><div className="mini-timeline"><div><i/><span><strong>12 Mac 2026</strong><p>Intervensi bacaan suku kata KV</p></span></div><div><i/><span><strong>25 Mac 2026</strong><p><b>KP4 → KP6</b> · Meningkat</p></span></div><div><i/><span><strong>10 April 2026</strong><p>Intervensi perkataan KVK</p></span></div></div></section></main><footer><button className="outline"><FileText size={17}/>Cetak Profil</button><button className="primary" onClick={intervention}><Plus size={17}/>Rekod Intervensi</button></footer></aside></div>}
function Title({title,desc,children}:{title:string;desc:string;children?:React.ReactNode}){return <div className="section-title"><span><h3>{title}</h3><p>{desc}</p></span>{children}</div>}
function Modal({title,desc,close,children,footer}:{title:string;desc:string;close:()=>void;children:React.ReactNode;footer:React.ReactNode}){return <div className="layer modal-layer"><button className="backdrop" onClick={close}/><div className="modal"><header><span><h2>{title}</h2><p>{desc}</p></span><button className="icon" onClick={close}><X size={20}/></button></header><main>{children}</main><footer>{footer}</footer></div></div>}

function AddModal({close,save}:{close:()=>void;save:(s:Student)=>void}){const [name,setName]=useState(""),[year,setYear]=useState(1),[className,setClass]=useState("1 Cekal"),[subject,setSubject]=useState<Subject>("Bahasa Melayu");const submit=()=>name.trim()&&save({id:`ST${String(Date.now()).slice(-4)}`,name:name.trim(),year,className,subject,status:"Aktif",startDate:"2026-08-13",skills:S(1,1,1,1,10),intervention:"Tiada"});return <Modal title="Tambah Murid" desc="Masukkan maklumat asas murid Pemulihan Khas." close={close} footer={<><button className="outline" onClick={close}>Batal</button><button className="primary" disabled={!name.trim()} onClick={submit}><Plus size={17}/>Tambah Murid</button></>}><div className="form-grid"><label className="full">Nama murid<input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="Nama penuh murid"/></label><label>Tahun<select value={year} onChange={e=>setYear(Number(e.target.value))}><option value="1">Tahun 1</option><option value="2">Tahun 2</option><option value="3">Tahun 3</option></select></label><label>Kelas<input value={className} onChange={e=>setClass(e.target.value)}/></label><label className="full">Mata pelajaran<select value={subject} onChange={e=>setSubject(e.target.value as Subject)}><option>Bahasa Melayu</option><option>Matematik</option></select></label><label className="full">Tarikh mula Pemulihan<input type="date" defaultValue="2026-08-13"/></label></div></Modal>}

function InterventionModal({students,selected,close,save}:{students:Student[];selected:Student|null;close:()=>void;save:(i:Intervention)=>void}){const [studentId,setStudentId]=useState(selected?.id||students[0].id),[issue,setIssue]=useState("Lemah membaca perkataan"),[action,setAction]=useState(""),[method,setMethod]=useState("Bimbingan individu");const student=students.find(s=>s.id===studentId)!;return <Modal title="Rekod Intervensi" desc="Rancang tindakan berdasarkan keperluan murid." close={close} footer={<><button className="outline" onClick={close}>Batal</button><button className="primary" disabled={!action.trim()} onClick={()=>save({id:`IV${Date.now()}`,studentId,issue,action,method,start:"2026-08-13",review:"2026-08-27",status:"Sedang dilaksanakan"})}><Check size={17}/>Simpan Intervensi</button></>}><div className="intervention-form"><label>Murid<select value={studentId} onChange={e=>setStudentId(e.target.value)}>{students.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><div className="selected-summary"><b>{initials(student.name)}</b><span><strong>{student.name}</strong><small>{student.className} · Kemahiran semasa {kp(student.skills["AR 3"])}</small></span></div><label>Isu dikenal pasti<select value={issue} onChange={e=>setIssue(e.target.value)}><option>Keliru huruf</option><option>Lemah membunyikan suku kata</option><option>Lemah menggabung suku kata</option><option>Lemah membaca perkataan</option><option>Lemah menulis</option><option>Tidak mengingat kemahiran</option><option>Kurang fokus</option><option>Kehadiran</option></select></label><label>Intervensi dilaksanakan<textarea rows={3} value={action} onChange={e=>setAction(e.target.value)} placeholder="Contoh: Latihan bacaan perkataan KVK menggunakan kad imbas."/></label><div className="form-grid"><label>Kaedah<select value={method} onChange={e=>setMethod(e.target.value)}><option>Bimbingan individu</option><option>Kumpulan kecil</option><option>Latih tubi</option><option>Permainan</option><option>ABM manipulatif</option><option>Bacaan berulang</option></select></label><label>Kekerapan<select><option>3 kali seminggu</option><option>2 kali seminggu</option><option>Setiap hari</option></select></label><label>Tarikh mula<input type="date" defaultValue="2026-08-13"/></label><label>Tarikh semakan<input type="date" defaultValue="2026-08-27"/></label></div><label className="upload"><Upload size={20}/><span><strong>Muat naik evidens</strong><small>Gambar atau PDF, maksimum 10MB</small></span><input type="file" accept="image/*,.pdf"/></label></div></Modal>}

function Confirm({cycle,close,confirm}:{cycle:Cycle;close:()=>void;confirm:()=>void}){return <Modal title={`Hantar Data ${cycle}?`} desc="Data akan dihantar kepada admin untuk semakan." close={close} footer={<><button className="outline" onClick={close}>Kembali</button><button className="primary" onClick={confirm}><Upload size={17}/>Ya, Hantar Data</button></>}><div className="confirm"><i><ClipboardCheck size={26}/></i><h3>Pastikan semua rekod telah lengkap</h3><p>Selepas admin mengesahkan dan mengunci cycle ini, data tidak boleh diubah tanpa kebenaran admin.</p><span><CheckCircle2 size={17}/>25 rekod murid lengkap</span><span><CheckCircle2 size={17}/>Tiada kemahiran tidak sah</span></div></Modal>}
